name: Test

on:
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [test]
  workflow_dispatch: # for manual testing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install dependencies
        run: npm ci

      # test code
      - name: Run tests
        run: npm test
